### ISSUE TITLE
Selecionar/desselecionar todos os checkbox

### ISSUE THREAD

**Issue by eshiota** [chesterbr/cruzalinhas#6]
Todas as vezes que eu usei o Cruzalinhas, eu senti falta de uma opção pra selecionar ou desselecionar todos os checkbox. Chega uma hora em que o mapa fica muito carregado, e eu vou desselecionando um por um para limpá-lo.

**Comment by chesterbr** [comment]
Em algum momento eu acabei implementando isso, mas esqueci de fechar o issue :cat: 
(e as instruções de bootstrap, embora a coisa esteja bem mais simples agora)
